'use client';

import Footer from '@/components/Footer';
import { parseInputs } from '@/lib/model';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';

function DashboardClient() {
  const searchParams = useSearchParams();
  const inputs = useMemo(() => parseInputs(Object.fromEntries(searchParams.entries())), [searchParams]);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const qs = new URLSearchParams(
      Object.entries(inputs).reduce((acc, [k, v]) => {
        acc[k] = String(v);
        return acc;
      }, {}),
    );

    let cancelled = false;
    setLoading(true);
    setError('');

    fetch(`/api/simulate?${qs.toString()}`)
      .then(async (res) => {
        const contentType = res.headers.get('content-type') || '';
        const isJson = contentType.includes('application/json');
        const body = isJson ? await res.json() : await res.text();

        if (!res.ok) {
          const details = isJson
            ? (body?.details || body?.error || 'Simulation request failed')
            : `Simulation endpoint returned ${res.status} ${res.statusText}.`;
          throw new Error(details);
        }

        if (!isJson) {
          throw new Error(
            'Simulation endpoint returned HTML instead of JSON. Restart Next server (`npm run dev`) and ensure `/api/simulate` is available.',
          );
        }

        if (!cancelled) {
          setResult(body);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err.message || 'Failed to load simulation');
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [inputs]);

  return (
    <div className="container" style={{ maxWidth: 1100 }}>
      <h1 className="section-title">Dashboard</h1>
      <p className="note">
        Inputs: industry={inputs.industry}, company={inputs.company_size}, level={inputs.job_level}, salary=${inputs.salary.toLocaleString()}, paths={inputs.n_paths}, horizon={inputs.horizon_years}y
      </p>

      {loading && <p className="note">Running full Monte Carlo model...</p>}
      {error && <p className="note" style={{ color: '#b42318' }}>Model error: {error}</p>}
      {!loading && !error && result && (
        <>
      <div className="metric-grid">
        <div className="metric"><div className="label">Average income (no hedge)</div><div className="value">${Math.round(result.meanNo).toLocaleString()}</div></div>
        <div className="metric"><div className="label">Average income (with hedge)</div><div className="value">${Math.round(result.meanHedge).toLocaleString()}</div></div>
        <div className="metric"><div className="label">Worst 5% outcomes</div><div className="value">${Math.round(result.worstNo).toLocaleString()} → ${Math.round(result.worstHedge).toLocaleString()}</div></div>
        <div className="metric"><div className="label">Big drop chance</div><div className="value">{result.tailNo.toFixed(1)}% → {result.tailHedge.toFixed(1)}%</div></div>
        <div className="metric"><div className="label">Contracts to buy</div><div className="value">{result.contracts.toLocaleString()}</div></div>
        <div className="metric"><div className="label">Upfront hedge cost</div><div className="value">${result.totalCost.toLocaleString()}</div></div>
      </div>

      <div className="card" style={{ marginTop: '1.25rem' }}>
        <p>
          <strong>Bottom line:</strong> Buy <strong>{result.contracts.toLocaleString()} contracts</strong> that pay out if US unemployment exceeds {result.hedgeThreshold.toFixed(1)}%.
          Upfront cost is <strong>${result.totalCost.toLocaleString()}</strong>. If triggered, payout is <strong>${result.payout.toLocaleString()}</strong>.
          In this model run, trigger chance is about <strong>{result.triggerRate.toFixed(1)}%</strong>.
        </p>
      </div>

      <div className="card" style={{ marginTop: '1rem' }}>
        <h3>Model assumptions</h3>
        <p className="note">Metrics are generated by the full hazard + Poisson + Monte Carlo pipeline, not fixed formulas.</p>
      </div>
      </>
      )}

      <Footer />
    </div>
  );
}

export default function DashboardPage() {
  return (
    <Suspense fallback={<div className="container"><p className="note">Loading dashboard...</p></div>}>
      <DashboardClient />
    </Suspense>
  );
}
